"""Alembic environment.

The URL and the metadata both come from the app rather than from alembic.ini, so
there is exactly one place that decides which database is in play and one
definition of the schema.
"""

import asyncio
from logging.config import fileConfig

from alembic import context
from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

from app.config import get_settings
from app.models import Base

config = context.config
config.set_main_option("sqlalchemy.url", get_settings().database_url)

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


def _skip_sqlite_foreign_key_churn(context, revision, directives) -> None:
    """Drop foreign-key add/remove pairs from autogenerated migrations.

    SQLite reflects foreign keys without names, so every autogenerate proposes
    dropping and recreating every one of them. That is noise, it never represents a
    real change, and on batch mode it can fail outright.
    """
    if not directives or context.dialect.name != "sqlite":
        return

    for op_container in directives[0].upgrade_ops.ops:
        if hasattr(op_container, "ops"):
            op_container.ops = [
                op
                for op in op_container.ops
                if type(op).__name__ not in {"CreateForeignKeyOp", "DropConstraintOp"}
            ]
    directives[0].upgrade_ops.ops = [
        op for op in directives[0].upgrade_ops.ops if not (hasattr(op, "ops") and not op.ops)
    ]


def _configure(connection: Connection) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        compare_type=True,
        # SQLite cannot ALTER most things; batch mode rewrites the table instead,
        # which is what makes a column change possible at all on the dev database.
        render_as_batch=connection.dialect.name == "sqlite",
        process_revision_directives=_skip_sqlite_foreign_key_churn,
    )


def run_migrations_offline() -> None:
    context.configure(
        url=config.get_main_option("sqlalchemy.url"),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        render_as_batch=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    _configure(connection)
    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)
    await connectable.dispose()


def run_migrations_online() -> None:
    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
