"""initial schema

Revision ID: 5188c5e13f74
Revises:
Create Date: 2026-09-07 21:33:04.414647

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.models


# revision identifiers, used by Alembic.
revision: str = "5188c5e13f74"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "concepts",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", app.models.UtcDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", app.models.UtcDateTime(timezone=True), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("section", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("concepts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_concepts_section"), ["section"], unique=False)
        batch_op.create_index(batch_op.f("ix_concepts_user_id"), ["user_id"], unique=False)

    op.create_table(
        "mistakes",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", app.models.UtcDateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=200), nullable=True),
        sa.Column("section", sa.String(length=32), nullable=False),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column("choices", sa.JSON(), nullable=True),
        sa.Column("your_answer", sa.Text(), nullable=False),
        sa.Column("correct_answer", sa.Text(), nullable=False),
        sa.Column("student_note", sa.Text(), nullable=True),
        sa.Column("analysis_status", sa.String(length=16), nullable=False),
        sa.Column("analysis_error", sa.Text(), nullable=True),
        sa.Column("analyzed_at", app.models.UtcDateTime(timezone=True), nullable=True),
        sa.Column("analyzed_by", sa.String(length=64), nullable=True),
        sa.Column("analysis_edited_at", app.models.UtcDateTime(timezone=True), nullable=True),
        sa.Column("error_type", sa.String(length=32), nullable=True),
        sa.Column("topic", sa.String(length=120), nullable=True),
        sa.Column("difficulty", sa.String(length=16), nullable=True),
        sa.Column("urgency", sa.String(length=20), nullable=True),
        sa.Column("why_wrong", sa.Text(), nullable=True),
        sa.Column("correct_reasoning", sa.Text(), nullable=True),
        sa.Column("takeaway", sa.Text(), nullable=True),
        sa.Column("trap", sa.Text(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("mistakes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_mistakes_analysis_status"), ["analysis_status"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_mistakes_error_type"), ["error_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_mistakes_topic"), ["topic"], unique=False)
        batch_op.create_index(batch_op.f("ix_mistakes_urgency"), ["urgency"], unique=False)
        batch_op.create_index(batch_op.f("ix_mistakes_user_id"), ["user_id"], unique=False)

    op.create_table(
        "concept_images",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("concept_id", sa.String(length=32), nullable=False),
        sa.Column("created_at", app.models.UtcDateTime(timezone=True), nullable=False),
        sa.Column("filename", sa.String(length=80), nullable=False),
        sa.Column("content_type", sa.String(length=64), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("caption", sa.String(length=200), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["concept_id"], ["concepts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("concept_images", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_concept_images_concept_id"), ["concept_id"], unique=False
        )

    op.create_table(
        "concept_mistakes",
        sa.Column("concept_id", sa.String(length=32), nullable=False),
        sa.Column("mistake_id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["concept_id"], ["concepts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["mistake_id"], ["mistakes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("concept_id", "mistake_id"),
    )
    op.create_table(
        "mistake_images",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("mistake_id", sa.String(length=32), nullable=False),
        sa.Column("created_at", app.models.UtcDateTime(timezone=True), nullable=False),
        sa.Column("filename", sa.String(length=80), nullable=False),
        sa.Column("content_type", sa.String(length=64), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("caption", sa.String(length=200), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["mistake_id"], ["mistakes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("mistake_images", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_mistake_images_mistake_id"), ["mistake_id"], unique=False
        )

    op.create_table(
        "review_events",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("mistake_id", sa.String(length=32), nullable=False),
        sa.Column("cycle", sa.Integer(), nullable=False),
        sa.Column("step_index", sa.Integer(), nullable=False),
        sa.Column("interval_label", sa.String(length=8), nullable=False),
        sa.Column("due_at", app.models.UtcDateTime(timezone=True), nullable=False),
        sa.Column("completed_at", app.models.UtcDateTime(timezone=True), nullable=True),
        sa.Column("outcome", sa.String(length=16), nullable=True),
        sa.ForeignKeyConstraint(["mistake_id"], ["mistakes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("review_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_review_events_due_at"), ["due_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_review_events_mistake_id"), ["mistake_id"], unique=False
        )
        batch_op.create_index("ix_review_events_open", ["completed_at", "due_at"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("review_events", schema=None) as batch_op:
        batch_op.drop_index("ix_review_events_open")
        batch_op.drop_index(batch_op.f("ix_review_events_mistake_id"))
        batch_op.drop_index(batch_op.f("ix_review_events_due_at"))

    op.drop_table("review_events")
    with op.batch_alter_table("mistake_images", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_mistake_images_mistake_id"))

    op.drop_table("mistake_images")
    op.drop_table("concept_mistakes")
    with op.batch_alter_table("concept_images", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_concept_images_concept_id"))

    op.drop_table("concept_images")
    with op.batch_alter_table("mistakes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_mistakes_user_id"))
        batch_op.drop_index(batch_op.f("ix_mistakes_urgency"))
        batch_op.drop_index(batch_op.f("ix_mistakes_topic"))
        batch_op.drop_index(batch_op.f("ix_mistakes_error_type"))
        batch_op.drop_index(batch_op.f("ix_mistakes_analysis_status"))

    op.drop_table("mistakes")
    with op.batch_alter_table("concepts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_concepts_user_id"))
        batch_op.drop_index(batch_op.f("ix_concepts_section"))

    op.drop_table("concepts")
    # ### end Alembic commands ###
