"""patterns the analyzer names

Revision ID: f5f4cda415b7
Revises: a59cdac11524
Create Date: 2026-09-26 14:48:30.518971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# The models module defines custom column types (UtcDateTime) that autogenerate
# renders by their fully qualified name; without this import the migration is a
# NameError at run time.
import app.models


# revision identifiers, used by Alembic.
revision: str = 'f5f4cda415b7'
down_revision: Union[str, Sequence[str], None] = 'a59cdac11524'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patterns',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', app.models.UtcDateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', app.models.UtcDateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patterns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patterns_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_patterns_user_id'), ['user_id'], unique=False)

    op.create_table('pattern_mistakes',
    sa.Column('pattern_id', sa.String(length=32), nullable=False),
    sa.Column('mistake_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['mistake_id'], ['mistakes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pattern_id'], ['patterns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pattern_id', 'mistake_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pattern_mistakes')
    with op.batch_alter_table('patterns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patterns_user_id'))
        batch_op.drop_index(batch_op.f('ix_patterns_slug'))

    op.drop_table('patterns')
    # ### end Alembic commands ###
