"""patterns can become concepts

Revision ID: fce778c22214
Revises: f5f4cda415b7
Create Date: 2026-09-30 22:47:24.289222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# The models module defines custom column types (UtcDateTime) that autogenerate
# renders by their fully qualified name; without this import the migration is a
# NameError at run time.
import app.models


# revision identifiers, used by Alembic.
revision: str = 'fce778c22214'
down_revision: Union[str, Sequence[str], None] = 'f5f4cda415b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patterns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('promoted_concept_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('dismissed_at', app.models.UtcDateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Autogenerate emits `drop_constraint(None, type_='foreignkey')` here, which
    # is the stub it asks you to adjust: an unnamed constraint cannot be dropped
    # and it raises "Constraint must have a name". Batch mode rebuilds the table
    # from the remaining columns anyway, so dropping the column takes its foreign
    # key with it.
    with op.batch_alter_table('patterns', schema=None) as batch_op:
        batch_op.drop_column('dismissed_at')
        batch_op.drop_column('promoted_concept_id')

    # ### end Alembic commands ###
