"""videos and subject tabs

Revision ID: ff27281f9d7e
Revises: fce778c22214
Create Date: 2026-09-30 22:53:57.727474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# The models module defines custom column types (UtcDateTime) that autogenerate
# renders by their fully qualified name; without this import the migration is a
# NameError at run time.
import app.models


# revision identifiers, used by Alembic.
revision: str = 'ff27281f9d7e'
down_revision: Union[str, Sequence[str], None] = 'fce778c22214'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', app.models.UtcDateTime(timezone=True), nullable=False),
    sa.Column('youtube_id', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('subject', sa.String(length=60), nullable=True),
    sa.Column('directions', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('summarised_at', app.models.UtcDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_videos_subject'), ['subject'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_videos_youtube_id'), ['youtube_id'], unique=False)

    with op.batch_alter_table('concepts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('video_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('start_seconds', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_concepts_subject'), ['subject'], unique=False)
        batch_op.create_index(batch_op.f('ix_concepts_video_id'), ['video_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Autogenerate emits two `drop_constraint(None, type_='foreignkey')` stubs
    # here — one of them against `patterns`, which this migration never touched.
    # An unnamed constraint cannot be dropped ("Constraint must have a name"), and
    # batch mode rebuilds the table from the remaining columns anyway, so dropping
    # the column takes its foreign key with it.
    with op.batch_alter_table('concepts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_concepts_video_id'))
        batch_op.drop_index(batch_op.f('ix_concepts_subject'))
        batch_op.drop_column('start_seconds')
        batch_op.drop_column('video_id')
        batch_op.drop_column('subject')

    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_videos_youtube_id'))
        batch_op.drop_index(batch_op.f('ix_videos_user_id'))
        batch_op.drop_index(batch_op.f('ix_videos_subject'))

    op.drop_table('videos')
    # ### end Alembic commands ###
